package view;

import controller.LogTrack;
import model.Usuario;

public class JFrameAppPrincipal extends javax.swing.JFrame {
    
    private Usuario usuario; // usuário logado

    public JFrameAppPrincipal() {
        initComponents();
        
        logout();
    }
    
    private void logout() {
        
        usuario = new Usuario();
        
        jMenuAdministrativo.setEnabled(false);
        jMenuAtendimento.setEnabled(false);
        
        jMenuUsuario.setVisible(false);
        
        jPanelLogin.setVisible(true);
        
    }
    
    private void login() {
        
        jMenuUsuario.setText( usuario.getNomeCompleto() );
        jMenuUsuario.setVisible(true);
        
        jTextFieldUsuario.setText("");
        jPasswordFieldSenha.setText("");
        
        jPanelLogin.setVisible(false);
        
        if( usuario.getTipoUsuario().getModuloAdministrativo().equals("S") ) {
            jMenuAdministrativo.setEnabled(true);
        }
        
        if( usuario.getTipoUsuario().getModuloAtendimento().equals("S") ) {
            jMenuAtendimento.setEnabled(true);
        }
               
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogin = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jLabelImagemFundoCRUD = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuAdministrativo = new javax.swing.JMenu();
        jMenuItemConsultaLivros = new javax.swing.JMenuItem();
        jMenuItemConsultaAutores = new javax.swing.JMenuItem();
        jMenuItemConsultaEditoras = new javax.swing.JMenuItem();
        jMenuItemConsultaGeneros = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCadastroLivros = new javax.swing.JMenuItem();
        jMenuItemCadastroAutores = new javax.swing.JMenuItem();
        jMenuItemCadastroEditoras = new javax.swing.JMenuItem();
        jMenuItemCadastroGeneros = new javax.swing.JMenuItem();
        jMenuAtendimento = new javax.swing.JMenu();
        jMenuItemAtendimentoConsultaExemplares = new javax.swing.JMenuItem();
        jMenuItemAtendimentoConsultaEmprestimos = new javax.swing.JMenuItem();
        jMenuItemAtendimentoConsultaMultas = new javax.swing.JMenuItem();
        jMenuItemAtendimentoConsultaUsuarios = new javax.swing.JMenuItem();
        jMenuItemAtendimentoConsultaResenhas = new javax.swing.JMenuItem();
        jMenuItemAtendimentoConsultaTipoUsuario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAtendimentoCadastroExemplares = new javax.swing.JMenuItem();
        jMenuItemAtendimentoCadastroEmprestimos = new javax.swing.JMenuItem();
        jMenuItemAtendimentoCadastroMultas = new javax.swing.JMenuItem();
        jMenuItemAtendimentoCadastroUsuarios = new javax.swing.JMenuItem();
        jMenuItemAtendimentoCadastroTipoUsuario = new javax.swing.JMenuItem();
        jMenuUsuario = new javax.swing.JMenu();
        jMenuItemMinhasMultas = new javax.swing.JMenuItem();
        jMenuItemMeusEmprestimos = new javax.swing.JMenuItem();
        jMenuItemMinhasResenhas = new javax.swing.JMenuItem();
        jMenuItemCadastroResenhas = new javax.swing.JMenuItem();
        jMenuItemExemplaresDisponiveis = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gerenciamento de Biblioteca");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLogin.setBackground(new java.awt.Color(0, 0, 0));
        jPanelLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuário");

        jLabelSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha.setText("Senha");

        jButtonLogin.setBackground(new java.awt.Color(102, 102, 102));
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLoginLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSenha)
                            .addComponent(jLabelUsuario)
                            .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLogin)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabelImagemFundoCRUD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/fundo_login.jpg"))); // NOI18N
        getContentPane().add(jLabelImagemFundoCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 320));

        jMenuAdministrativo.setText("Administrativo");

        jMenuItemConsultaLivros.setText("Consulta Livros");
        jMenuItemConsultaLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaLivrosActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemConsultaLivros);

        jMenuItemConsultaAutores.setText("Consulta Autores");
        jMenuItemConsultaAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaAutoresActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemConsultaAutores);

        jMenuItemConsultaEditoras.setText("Consulta Editoras");
        jMenuItemConsultaEditoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaEditorasActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemConsultaEditoras);

        jMenuItemConsultaGeneros.setText("Consulta Gêneros");
        jMenuItemConsultaGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaGenerosActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemConsultaGeneros);
        jMenuAdministrativo.add(jSeparator1);

        jMenuItemCadastroLivros.setText("Cadastro Livros");
        jMenuItemCadastroLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroLivrosActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemCadastroLivros);

        jMenuItemCadastroAutores.setText("Cadastro Autores");
        jMenuItemCadastroAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroAutoresActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemCadastroAutores);

        jMenuItemCadastroEditoras.setText("Cadastro Editoras");
        jMenuItemCadastroEditoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroEditorasActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemCadastroEditoras);

        jMenuItemCadastroGeneros.setText("Cadastro Gêneros");
        jMenuItemCadastroGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroGenerosActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemCadastroGeneros);

        jMenuBar.add(jMenuAdministrativo);

        jMenuAtendimento.setText("Atendimento");

        jMenuItemAtendimentoConsultaExemplares.setText("Consulta Exemplares");
        jMenuItemAtendimentoConsultaExemplares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtendimentoConsultaExemplaresActionPerformed(evt);
            }
        });
        jMenuAtendimento.add(jMenuItemAtendimentoConsultaExemplares);

        jMenuItemAtendimentoConsultaEmprestimos.setText("Consulta Empréstimos");
        jMenuItemAtendimentoConsultaEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtendimentoConsultaEmprestimosActionPerformed(evt);
            }
        });
        jMenuAtendimento.add(jMenuItemAtendimentoConsultaEmprestimos);

        jMenuItemAtendimentoConsultaMultas.setText("Consulta Multas");
        jMenuItemAtendimentoConsultaMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtendimentoConsultaMultasActionPerformed(evt);
            }
        });
        jMenuAtendimento.add(jMenuItemAtendimentoConsultaMultas);

        jMenuItemAtendimentoConsultaUsuarios.setText("Consulta Usuários");
        jMenuItemAtendimentoConsultaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtendimentoConsultaUsuariosActionPerformed(evt);
            }
        });
        jMenuAtendimento.add(jMenuItemAtendimentoConsultaUsuarios);

        jMenuItemAtendimentoConsultaResenhas.setText("Consulta Resenhas");
        jMenuItemAtendimentoConsultaResenhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtendimentoConsultaResenhasActionPerformed(evt);
            }
        });
        jMenuAtendimento.add(jMenuItemAtendimentoConsultaResenhas);

        jMenuItemAtendimentoConsultaTipoUsuario.setText("Consulta Tipo Usuário");
        jMenuItemAtendimentoConsultaTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtendimentoConsultaTipoUsuarioActionPerformed(evt);
            }
        });
        jMenuAtendimento.add(jMenuItemAtendimentoConsultaTipoUsuario);
        jMenuAtendimento.add(jSeparator2);

        jMenuItemAtendimentoCadastroExemplares.setText("Cadastro Exemplares");
        jMenuItemAtendimentoCadastroExemplares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtendimentoCadastroExemplaresActionPerformed(evt);
            }
        });
        jMenuAtendimento.add(jMenuItemAtendimentoCadastroExemplares);

        jMenuItemAtendimentoCadastroEmprestimos.setText("Cadastro Empréstimos");
        jMenuItemAtendimentoCadastroEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtendimentoCadastroEmprestimosActionPerformed(evt);
            }
        });
        jMenuAtendimento.add(jMenuItemAtendimentoCadastroEmprestimos);

        jMenuItemAtendimentoCadastroMultas.setText("Cadastro Multas");
        jMenuItemAtendimentoCadastroMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtendimentoCadastroMultasActionPerformed(evt);
            }
        });
        jMenuAtendimento.add(jMenuItemAtendimentoCadastroMultas);

        jMenuItemAtendimentoCadastroUsuarios.setText("Cadastro Usuários");
        jMenuItemAtendimentoCadastroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtendimentoCadastroUsuariosActionPerformed(evt);
            }
        });
        jMenuAtendimento.add(jMenuItemAtendimentoCadastroUsuarios);

        jMenuItemAtendimentoCadastroTipoUsuario.setText("Cadastro Tipo Usuário");
        jMenuItemAtendimentoCadastroTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtendimentoCadastroTipoUsuarioActionPerformed(evt);
            }
        });
        jMenuAtendimento.add(jMenuItemAtendimentoCadastroTipoUsuario);

        jMenuBar.add(jMenuAtendimento);

        jMenuUsuario.setText("Usuário");

        jMenuItemMinhasMultas.setText("Minhas Multas");
        jMenuItemMinhasMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMinhasMultasActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemMinhasMultas);

        jMenuItemMeusEmprestimos.setText("Meus Empréstimos");
        jMenuItemMeusEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMeusEmprestimosActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemMeusEmprestimos);

        jMenuItemMinhasResenhas.setText("Minhas Resenhas");
        jMenuItemMinhasResenhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMinhasResenhasActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemMinhasResenhas);

        jMenuItemCadastroResenhas.setText("Cadastrar uma Resenha");
        jMenuItemCadastroResenhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroResenhasActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemCadastroResenhas);

        jMenuItemExemplaresDisponiveis.setText("Exemplares Disponíveis");
        jMenuItemExemplaresDisponiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExemplaresDisponiveisActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemExemplaresDisponiveis);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemSair);

        jMenuBar.add(jMenuUsuario);

        setJMenuBar(jMenuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastroAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroAutoresActionPerformed
        // TODO add your handling code here:
        try {
            JFrameAutorCRUD jFrameCRUD;
            jFrameCRUD = new JFrameAutorCRUD( null, true );
            jFrameCRUD.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemCadastroAutoresActionPerformed

    private void jMenuItemCadastroEditorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroEditorasActionPerformed
        // TODO add your handling code here:
        try {
            JFrameEditoraCRUD jFrameCRUD;
            jFrameCRUD = new JFrameEditoraCRUD( null, true );
            jFrameCRUD.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemCadastroEditorasActionPerformed

    private void jMenuItemConsultaAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaAutoresActionPerformed
        // TODO add your handling code here:
        try {
            JFrameConsultaAutor jFrameConsulta;
            jFrameConsulta = new JFrameConsultaAutor( false, true, null );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemConsultaAutoresActionPerformed

    private void jMenuItemConsultaEditorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaEditorasActionPerformed
        // TODO add your handling code here:
        try {
            JFrameConsultaEditora jFrameConsulta;
            jFrameConsulta = new JFrameConsultaEditora( false, true, null );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemConsultaEditorasActionPerformed

    private void jMenuItemConsultaLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaLivrosActionPerformed
        // TODO add your handling code here:
        try {
            JFrameConsultaLivro jFrameConsulta;
            jFrameConsulta = new JFrameConsultaLivro( false, true, null, true);
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemConsultaLivrosActionPerformed

    private void jMenuItemConsultaGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaGenerosActionPerformed
        // TODO add your handling code here:
        try {
            JFrameConsultaGenero jFrameConsulta;
            jFrameConsulta = new JFrameConsultaGenero( false, true, null );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemConsultaGenerosActionPerformed

    private void jMenuItemCadastroLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroLivrosActionPerformed
        // TODO add your handling code here:
        try {
            JFrameLivroCRUD jFrameCRUD;
            jFrameCRUD = new JFrameLivroCRUD( null, true );
            jFrameCRUD.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemCadastroLivrosActionPerformed

    private void jMenuItemCadastroGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroGenerosActionPerformed
        // TODO add your handling code here:     
        try {
            JFrameGeneroCRUD jFrameCRUD;
            jFrameCRUD = new JFrameGeneroCRUD( null, true );
            jFrameCRUD.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemCadastroGenerosActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
        
        try {
            
            usuario.setCodigoUsuario( Integer.parseInt( jTextFieldUsuario.getText() ) );
            usuario.load();
            
            Usuario usLogin = new Usuario();
            
            usLogin.setCodigoUsuario( Integer.parseInt( jTextFieldUsuario.getText() ) );
            usLogin.setSenhaAcesso( jPasswordFieldSenha.getText() );
            
            if( usuario.getSenhaAcesso().equals( 
                    usLogin.getSenhaAcesso() ) ) {
                login();
                usuario.disconnectFromDatabase();
            } else {
                throw new Exception("Senha Inválida!");
            }
            
        
        } catch(Exception ex) {
            LogTrack.getInstance().addException( ex, true, this );
        }
         
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemAtendimentoConsultaExemplaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtendimentoConsultaExemplaresActionPerformed
        // TODO add your handling code here: 
        try {
            JFrameConsultaExemplar jFrameConsulta;
            jFrameConsulta = new JFrameConsultaExemplar( false, true, null, null, true );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemAtendimentoConsultaExemplaresActionPerformed

    private void jMenuItemMinhasMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMinhasMultasActionPerformed
        // TODO add your handling code here:
        try {
            JFrameConsultaMulta jFrameConsulta;
            jFrameConsulta = new JFrameConsultaMulta( false, true, null, usuario, false );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemMinhasMultasActionPerformed

    private void jMenuItemAtendimentoConsultaEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtendimentoConsultaEmprestimosActionPerformed
        // TODO add your handling code here:
        try {
            JFrameConsultaEmprestimo jFrameConsulta;
            jFrameConsulta = new JFrameConsultaEmprestimo( false, true, null, null, true );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemAtendimentoConsultaEmprestimosActionPerformed

    private void jMenuItemAtendimentoConsultaMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtendimentoConsultaMultasActionPerformed
        // TODO add your handling code here:
        try {
            JFrameConsultaMulta jFrameConsulta;
            jFrameConsulta = new JFrameConsultaMulta( false, true, null, null, true );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemAtendimentoConsultaMultasActionPerformed

    private void jMenuItemAtendimentoConsultaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtendimentoConsultaUsuariosActionPerformed
        // TODO add your handling code here:
        try {
            JFrameConsultaUsuario jFrameConsulta;
            jFrameConsulta = new JFrameConsultaUsuario( false, true, null, true );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemAtendimentoConsultaUsuariosActionPerformed

    private void jMenuItemAtendimentoConsultaResenhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtendimentoConsultaResenhasActionPerformed
        // TODO add your handling code here:
        try {
            JFrameConsultaResenha jFrameConsulta;
            jFrameConsulta = new JFrameConsultaResenha( false, true, null, null, true );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemAtendimentoConsultaResenhasActionPerformed

    private void jMenuItemAtendimentoConsultaTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtendimentoConsultaTipoUsuarioActionPerformed
        // TODO add your handling code here:
        try {
            JFrameConsultaTipoUsuario jFrameConsulta;
            jFrameConsulta = new JFrameConsultaTipoUsuario( false, true, null );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemAtendimentoConsultaTipoUsuarioActionPerformed

    private void jMenuItemAtendimentoCadastroExemplaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtendimentoCadastroExemplaresActionPerformed
        // TODO add your handling code here:
        try {
            JFrameExemplarCRUD jFrameCRUD;
            jFrameCRUD = new JFrameExemplarCRUD( null, true );
            jFrameCRUD.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemAtendimentoCadastroExemplaresActionPerformed

    private void jMenuItemAtendimentoCadastroEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtendimentoCadastroEmprestimosActionPerformed
        // TODO add your handling code here:
        try {
            JFrameEmprestimoCRUD jFrameCRUD;
            jFrameCRUD = new JFrameEmprestimoCRUD( null, true );
            jFrameCRUD.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemAtendimentoCadastroEmprestimosActionPerformed

    private void jMenuItemAtendimentoCadastroMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtendimentoCadastroMultasActionPerformed
        // TODO add your handling code here:
        try {
            JFrameMultaCRUD jFrameCRUD;
            jFrameCRUD = new JFrameMultaCRUD( null, true );
            jFrameCRUD.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemAtendimentoCadastroMultasActionPerformed

    private void jMenuItemAtendimentoCadastroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtendimentoCadastroUsuariosActionPerformed
        // TODO add your handling code here:
        try {
            JFrameUsuarioCRUD jFrameCRUD;
            jFrameCRUD = new JFrameUsuarioCRUD( null, true );
            jFrameCRUD.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemAtendimentoCadastroUsuariosActionPerformed

    private void jMenuItemAtendimentoCadastroTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtendimentoCadastroTipoUsuarioActionPerformed
        // TODO add your handling code here:
        try {
            JFrameTipoUsuarioCRUD jFrameCRUD;
            jFrameCRUD = new JFrameTipoUsuarioCRUD( null, true );
            jFrameCRUD.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemAtendimentoCadastroTipoUsuarioActionPerformed

    private void jMenuItemMeusEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMeusEmprestimosActionPerformed
        // TODO add your handling code here:
        try {
            JFrameConsultaEmprestimo jFrameConsulta;
            jFrameConsulta = new JFrameConsultaEmprestimo( false, true, null, usuario, false );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemMeusEmprestimosActionPerformed

    private void jMenuItemMinhasResenhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMinhasResenhasActionPerformed
        // TODO add your handling code here:
        try {
            JFrameConsultaResenha jFrameConsulta;
            jFrameConsulta = new JFrameConsultaResenha( false, true, null, usuario, false );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemMinhasResenhasActionPerformed

    private void jMenuItemCadastroResenhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroResenhasActionPerformed
        // TODO add your handling code here:
        try {
            JFrameResenhaCRUD jFrameCRUD;
            jFrameCRUD = new JFrameResenhaCRUD( null, true );
            jFrameCRUD.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemCadastroResenhasActionPerformed

    private void jMenuItemExemplaresDisponiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExemplaresDisponiveisActionPerformed
        // TODO add your handling code here:
        try {
            JFrameConsultaExemplar jFrameConsulta;
            jFrameConsulta = new JFrameConsultaExemplar( false, true, null, usuario, false );
            jFrameConsulta.setVisible(true);
        } catch( Exception ex ){
            LogTrack.getInstance().addException( ex, true, this );
        }
    }//GEN-LAST:event_jMenuItemExemplaresDisponiveisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAppPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAppPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAppPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAppPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
              
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAppPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabelImagemFundoCRUD;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenu jMenuAdministrativo;
    private javax.swing.JMenu jMenuAtendimento;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemAtendimentoCadastroEmprestimos;
    private javax.swing.JMenuItem jMenuItemAtendimentoCadastroExemplares;
    private javax.swing.JMenuItem jMenuItemAtendimentoCadastroMultas;
    private javax.swing.JMenuItem jMenuItemAtendimentoCadastroTipoUsuario;
    private javax.swing.JMenuItem jMenuItemAtendimentoCadastroUsuarios;
    private javax.swing.JMenuItem jMenuItemAtendimentoConsultaEmprestimos;
    private javax.swing.JMenuItem jMenuItemAtendimentoConsultaExemplares;
    private javax.swing.JMenuItem jMenuItemAtendimentoConsultaMultas;
    private javax.swing.JMenuItem jMenuItemAtendimentoConsultaResenhas;
    private javax.swing.JMenuItem jMenuItemAtendimentoConsultaTipoUsuario;
    private javax.swing.JMenuItem jMenuItemAtendimentoConsultaUsuarios;
    private javax.swing.JMenuItem jMenuItemCadastroAutores;
    private javax.swing.JMenuItem jMenuItemCadastroEditoras;
    private javax.swing.JMenuItem jMenuItemCadastroGeneros;
    private javax.swing.JMenuItem jMenuItemCadastroLivros;
    private javax.swing.JMenuItem jMenuItemCadastroResenhas;
    private javax.swing.JMenuItem jMenuItemConsultaAutores;
    private javax.swing.JMenuItem jMenuItemConsultaEditoras;
    private javax.swing.JMenuItem jMenuItemConsultaGeneros;
    private javax.swing.JMenuItem jMenuItemConsultaLivros;
    private javax.swing.JMenuItem jMenuItemExemplaresDisponiveis;
    private javax.swing.JMenuItem jMenuItemMeusEmprestimos;
    private javax.swing.JMenuItem jMenuItemMinhasMultas;
    private javax.swing.JMenuItem jMenuItemMinhasResenhas;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuUsuario;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
